apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: observatorium-metrics
  namespace: <namespace>
spec:
  datasources:
    - access: proxy
      editable: true
      secureJsonData:
        httpHeaderValue1: Bearer $OAUTH_TOKEN
      name: Observatorium-Metrics
      url: >-
        https://<observatorium_host>/api/metrics/v1/<tenant_id>
      jsonData:
        httpHeaderName1: Authorization
        timeInterval: 5s
        tlsSkipVerify: true
      isDefault: false
      version: 1
      type: prometheus
  name: observatorium-metrics.yaml