apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: monitoring-stack-operator
  namespace: openshift-operators
spec:
  channel: development
  installPlanApproval: Automatic
  name: monitoring-stack-operator
  source: monitoring-operators
  sourceNamespace: openshift-marketplace
  startingCSV: monitoring-stack-operator.v0.0.2