apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: <datasource-name>
  namespace: grafana
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer $OAUTH_TOKEN'  # OAUTH_TOKEN is stored as a secret
      type: prometheus
      url: <obs-url>
  name: <datasource-name>.yaml