{
 "title": "Starburst 12",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU USAGE (PODS)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"starburst-sb12\"}) by (pod)\n"
    }
   ]
  },
  {
   "title": "MEMORY USAGE (PODS)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"starburst-sb12\", container!=\"\", image!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "MEMORY USAGE (Deployments)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"\", namespace=\"starburst-sb12\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=\"starburst-sb12\", workload_type=\"deployment\"}\n) by (workload, workload_type)"
    }
   ]
  },
  {
   "title": "CPU USAGE (Deployments)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", namespace=\"starburst-sb12\"}\n* on(namespace,pod)\n  group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"\", namespace=\"starburst-sb12\", workload_type=\"deployment\"}\n) by (workload, workload_type)"
    }
   ]
  },
  {
   "title": "TRINO ACTIVE NODES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_active_nodes{namespace=\"starburst-sb12\"}"
    }
   ]
  },
  {
   "title": "JVM HEAP MEMORY USED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_heap_memory_used" }
   ]
  },
  {
   "title": "TRINO FREE MEMORY",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_free_memory{namespace=\"starburst-sb12\"}"
    }
   ]
  },
  {
   "title": "TRINO EXECUTION LATENCY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_execution_latency{namespace=\"starburst-sb12\"}"
    }
   ]
  },
  {
   "title": "TRINO FAILED QUERIES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_failed_queries_user{namespace=\"starburst-sb12\"}"
    }
   ]
  },
  {
   "title": "TRINO RUNNING QUERIES",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_queries_started{namespace=\"starburst-sb12\"}"
    }
   ]
  }
 ]
}