{
 "title": "Starburst-NS",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "ALERTS",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{severity=~\"page|acknowledged|warn\",alertstate=\"firing\"}"
    }
   ]
  },
  {
   "title": "Number of Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Trino active nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trino_active_nodes{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Trino free memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(trino_free_memory) by (namespace)"
    }
   ]
  },
  {
   "title": "Trino Execution Delay",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "trino_execution_latency" }
   ]
  },
  {
   "title": "Trino Failed Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trino_queries_failed_all{namespace=\"$namespace\"}) by ()"
    }
   ]
  },
  {
   "title": "JVM Total Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_classes_loaded_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "JVM heap memory used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_heap_memory_used{namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "JVM Max Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "JVM Heap Memory Commited",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_heap_memory_commited{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Overcommit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\"}) - sum(kube_node_status_capacity{resource=\"cpu\"}) "
    }
   ]
  },
  {
   "title": "Idle CPU Cores",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\",namespace=\"$namespace\"}[30m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$namespace\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "CPU Usage (Worker )",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", container=\"worker\",namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Usage(Worker pods)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container=\"worker\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Available coordinator pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=\"coordinator\",pod=\"prometheus-k8s-0\",namespace=\"$namespace\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Available worker pods(replicas)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kube_state" }
   ]
  },
  {
   "title": "CPU Usage(Coordinator pods)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"\", container=\"coordinator\",namespace=\"$namespace\"}) by (namespace)\n"
    }
   ]
  },
  {
   "title": "Unavailable worker pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"worker\",namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Unavailable coordinator pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=\"coordinator\",namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Usage(Coordinator pods)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container=\"coordinator\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Coordinator pods crashlooping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"coordinator\",namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Worker pod crashlooping",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"worker\",namespace=\"$namespace\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Total Waiting Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=\"$namespace\"}) by (namespace,pod)"
    }
   ]
  },
  {
   "title": "Unhealthy pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Pending|Unknown|Failed\",namespace=\"$namespace\"})"
    }
   ]
  }
 ]
}